//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciarSenhas.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Senha
    {
        public int ID { get; set; }
        public int IDUsuario { get; set; }

		[Required(ErrorMessage = "*Informe a senha")]
		[Display(Name = "Senha")]
		public string Senha1 { get; set; }

		[Required(ErrorMessage = "*Informe o local")]
		[Display(Name = "Local")]
		public string LocalS { get; set; }

		[Required(ErrorMessage = "*Informe a login")]
		[Display(Name = "Login")]
		public string LoginS { get; set; }

		public virtual Usuario Usuario { get; set; }
    }
}
