//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciarSenhas.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Senha1 = new HashSet<Senha>();
        }
    
        public int ID { get; set; }

		[Required(ErrorMessage = "*Informe o login")]
		[Display(Name = "Insira seu Login")]
		public string Login { get; set; }

		[Required(ErrorMessage = "*Informe a senha")]
		[DataType(DataType.Password)]
		[Display(Name = "Insira sua Senha")]
		public string Senha { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Senha> Senha1 { get; set; }
    }
}
